TOKEN = "5886515137:AAGze8jLm6y-OrKHWcRB2cMa1zm-tguXQp0"


DATABASE_USER = "root"
DATABASE_PASSWORD = "qwerty123"
DATABASE_HOST = "localhost"
DATABASE_NAME = "car_db"

# Ссылка на базу данных
MYSQL_URL = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"



